server:
  port: ${SERVER_PORT:8082}
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/wms}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${JPA_DDL:none}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:29092}
    consumer:
      group-id: wms-crp-group
      auto-offset-reset: latest
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: audit.events
  messages:
    basename: messages
    encoding: UTF-8
kafka:
  enabled: true

services:
  customer:
    base-url: ${CUSTOMER_BASE_URL:http://localhost:8080}
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    org.apache.kafka: ERROR
    org.apache.kafka.clients: ERROR
    org.springframework.kafka: ERROR
    reactor.netty: ERROR
    org.springframework.web: INFO
    com.wms.crp: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
springdoc:
  api-docs.enabled: true
  swagger-ui.enabled: true

security:
  jwt:
    secret: ${JWT_SECRET:dev-secret-change-me}
    issuer: ${JWT_ISSUER:wms-gateway}
    expMinutes: ${JWT_EXP_MIN:120}
